spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.bpulzavntnzmdkzfdxyb
spring.datasource.password=TransitHub2026!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your-256-bit-secret-minimum-32-chars-here-replace-this
jwt.expiration=86400000

server.port=8080